[[commands]]
package = "sbt"
category = "build"

[[commands]]
package = "scala-cli"
category = "build"

[[commands]]
name = "compile"
help = "Compile the project"
command = "sbt compile"
category = "build"

[[commands]]
name = "runTests"
help = "Run test suite"
command = "sbt test"
category = "test"

[[commands]]
name = "runApp"
help = "Run the application"
command = "sbt run"
category = "run"

[[commands]]
name = "runFormat"
help = "Format code with scalafmt"
command = "scalafmt --mode diff"
category = "format"

[[commands]]
name = "runFormatCheck"
help = "Check code formatting"
command = "scalafmt --check"
category = "format"

[[commands]]
name = "console"
help = "Start Scala REPL with project classes"
command = "sbt console"
category = "repl"

[[commands]]
name = "newScala3"
help = "Create new Scala 3 project in current directory"
command = "sbt new devinsideyou/scala3-seed.g8 -o ."
category = "init"

[[commands]]
name = "newTypelevel"
help = "Create new Typelevel project in current directory"
command = "sbt new typelevel/typelevel.g8 -o ."
category = "init"

[[commands]]
name = "newScala2"
help = "Create new Scala 2.13 project in current directory"
command = "sbt new devinsideyou/scala-seed.g8 -o ."
category = "init"
